<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SageRage.Console</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SageRage.Core\SageRage.Core.csproj" />
    <ProjectReference Include="..\SageRage.Proxy\SageRage.Proxy.csproj" />
  </ItemGroup>
</Project>
